FROM postgres:13.1

ENV POSTGRES_PASSWORD pass
ENV POSTGRES_USER user
ENV POSTGRES_DB main_db

# detached and port flags need to be after name of image. Args prior to the name go to the container
# docker run --name postgresql-dev -d -p 5432:5432 postgresql-dev
